image: atlassian/default-image:3
pipelines:
  branches:
    '*':
      - step:
          name: Sync GitHub Mirror
          image: alpine/git:latest
          clone:
            enabled: false
          script:
            - git clone --bare git@bitbucket.org:ckolivas/ckpool.git
            - cd ckpool.git
            - git push --mirror git@github.com:ckolivas/ckpool.git
